apiVersion: v1
kind: Service
metadata:
  name: doc-processor-service
  namespace: default
spec:
  selector:
    app: doc-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
